---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-dabbi-sqs-consumer
  namespace: keda-test
data:
  SQS_NAME: "dabbi-sqs"
  SQS_WAIT_TIME: "5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dabbi-sqs-consumer
  namespace: keda-test
  labels:
    app: dabbi-sqs-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dabbi-sqs-consumer
  template:
    metadata:
      labels:
        app: dabbi-sqs-consumer
    spec:
      containers:
      - image: 147026937442.dkr.ecr.ap-northeast-2.amazonaws.com/dabbi-sqs-consumer:0.0.3
        name: dabbi-sqs-consumer
        env:
        - name: SQS_NAME
          valueFrom:
            configMapKeyRef:
              name: cm-dabbi-sqs-consumer
              key: SQS_NAME
        - name: SQS_WAIT_TIME
          valueFrom:
            configMapKeyRef:
              name: cm-dabbi-sqs-consumer
              key: SQS_WAIT_TIME
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: test-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: test-secrets
              key: AWS_SECRET_ACCESS_KEY
